export const portfolioData = {
  personalInfo: {
    name: 'Israel Torres',
    fullName: 'Israel Torres',
    title: 'Ingeniero Civil Industrial · Strategy, Product & Applied AI',
    eyebrow: 'Strategy · CRM Lifecycle · Data & Applied AI',
    headline: 'No me quedo en lo básico: traduzco problemas de negocio en prototipos vivos y soluciones que mueven la aguja.',
    description: 'Soy Ingeniero Civil Industrial y actúo como el nexo que articula Negocio, Marketing, BI y Data Science. Mi día a día combina rigor organizativo con curiosidad activa: reservo tiempo deliberado para preguntarme cómo optimizar cada flujo con Inteligencia Artificial, y paso de la investigación y el benchmark al diseño de prototipos funcionales que aceleran la toma de decisiones.',
    email: 'itorresl@correo.uss.cl',
    linkedin: 'https://linkedin.com/in/israeltorresl',
    github: 'https://github.com/IsraelTorresIndustrial',
    location: 'Santiago, Chile',
  },
  heroScenarios: [
    {
      ask: '“Necesitamos presentar nuevos proyectos para Visa, pero la información de mercado e industria está dispersa.”',
      question: '¿Y si en lugar de un informe estático creamos benchmarks interactivos, flujos y prototipos que simulen la experiencia real?',
      outcome: 'Investigación de mercado, diseño de journeys y maquetas funcionales que destraban aprobaciones y dan vida a nuevas oportunidades comerciales.',
      label: 'De requerimiento a prototipo vivo',
    },
    {
      ask: '“¿Cómo conectamos los modelos de Data Science con las campañas comerciales sin perder trazabilidad?”',
      question: '¿Podemos orquestar journeys de ciclo de vida con supervisión de punta a punta entre BI, Analytics y Negocio?',
      outcome: 'Estrategias de adquisición, activación, uso y reactivación coordinadas con tableros ejecutivos en Power BI y planes de acción ágiles.',
      label: 'De silos a journeys coordinados',
    },
    {
      ask: '“La creación de briefs, piezas y seguimiento operativo consume demasiado tiempo del equipo.”',
      question: '¿Cómo apalancamos GenAI para liberar tiempo de ejecución y poner el foco en la estrategia?',
      outcome: 'Workflows automatizados y generación estructurada de piezas/HTML que multiplican la velocidad de iteración y aseguran consistencia.',
      label: 'De cuello de botella a aceleración con IA',
    },
  ],
  metrics: [
    { value: '2', label: 'países', description: 'Iniciativas regionales de Visa en Chile y Argentina.' },
    { value: '200+', label: 'pruebas QA', description: 'Casos de prueba para validación sistemática de copilotos IA.' },
    { value: '4+', label: 'áreas integradas', description: 'Articulación activa entre Negocio, Marketing, BI y Data Science.' },
    { value: '5+', label: 'prototipos', description: 'De maquetas de IA y benchmarks a herramientas web de gestión.' },
  ],
  trustedFor: [
    'Ser el nexo que traduce requerimientos de negocio en especificaciones para BI y Data Science',
    'Diseñar journeys y estrategias de ciclo de vida (adquisición, uso y reactivación) en medios de pago',
    'Darle vida a ideas construyendo prototipos funcionales de IA aplicada y herramientas web',
    'Cuestionar supuestos e investigar el mercado para ir siempre dos pasos más allá del encargo básico',
  ],
  principles: [
    {
      number: '01',
      title: 'Ir dos pasos más allá',
      description: 'No me quedo en recibir un encargo pasivamente. Investigo el contexto, cuestiono supuestos y busco la vuelta que transforme un requerimiento rutinario en una ventaja estratégica.',
      signal: 'Iniciativa & Visión',
    },
    {
      number: '02',
      title: 'Darle vida a las ideas',
      description: 'Una idea explicada en abstracto genera dudas; un prototipo interactivo genera certezas. Construyo maquetas funcionales y flujos reales para validar antes de escalar.',
      signal: 'Pensar haciendo',
    },
    {
      number: '03',
      title: 'Ser el nexo articulador',
      description: 'Hablo el idioma del negocio, el de los datos y el de la tecnología. Conecto a Data Science, Business Analysts y Marketing para asegurar que todo funcione de punta a punta.',
      signal: 'Orquestación transversal',
    },
    {
      number: '04',
      title: 'Optimización continua con IA',
      description: 'Me organizo con prioridades claras y reservo espacios deliberados para preguntarme: “¿Cómo puedo hacer esto más rápido, simple y escalable usando Inteligencia Artificial?”.',
      signal: 'Criterio & Automatización',
    },
  ],
  projects: [
    {
      id: 'presentation-engine',
      number: '01',
      short: 'HTML/LLM → PPT Engine',
      title: 'Generación de presentaciones ejecutivas en PPT desde HTML con LLMs',
      context: 'Innovación & Workflow Automation · Productividad',
      type: 'Generación con LLMs + HTML Canvas + Conversor PPTx',
      status: 'En producción interna',
      role: 'Diseño del workflow, lineamientos estructurados y conversión a PPTx',
      thesis: 'Armar presentaciones ejecutivas desde cero es un cuello de botella recurrente. Al darle lineamientos estrictos de estructura corporativa en HTML a los LLMs, se generan decks impactantes, trazables y exportables a PowerPoint editable en minutos.',
      problem: 'Crear decks ejecutivos con diseño de calidad, paleta coherente y jerarquía clara demandaba horas repetitivas de armado manual en cada iteración de proyecto.',
      build: 'Desarrollé una aplicación que traduce directrices de diseño corporativo a estructuras HTML que los LLMs (Gemini, Claude, GPT) completan con precisión. Luego, mediante automatización, se exporta a archivos PowerPoint (.pptx) editables conservando logos, colores, layout y tipografías.',
      value: 'Reducción de horas de trabajo a minutos, con presentaciones visualmente impactantes, 100% consistentes con la identidad de marca y editables por cualquier equipo.',
      facts: ['HTML semántico a PPTx', 'Paleta y logos 100% corporativos', 'Integración con LLMs', 'Reducción masiva de tiempos'],
      tags: ['LLMs', 'HTML to PPTx', 'Automation', 'Workflow Design', 'Productivity Engine', 'Claude/Gemini'],
      visual: 'presentation',
    },
    {
      id: 'copilot-rag',
      number: '02',
      short: 'Copiloto Comercial & RAG',
      title: 'Asistente conversacional de beneficios, campañas y políticas comerciales',
      context: 'Iniciativas Regionales · Medios de Pago & Banca',
      type: 'Chatbot RAG + Citas de Fuentes + QA Sistemático',
      status: 'Prototipo auditado (200+ tests)',
      role: 'Product Discovery, Prompt Engineering y Validación QA',
      thesis: 'La información de beneficios, condiciones y campañas suele estar dispersa en múltiples documentos. La IA debe estructurar el conocimiento institucional y responder con fuentes claras sin inventar respuestas.',
      problem: 'Ejecutivos comerciales y equipos internos perdían tiempo buscando condiciones exactas de campañas y medios de pago, generando demoras e inconsistencias ante clientes.',
      build: 'Desarrollo de un prototipo de chatbot con arquitectura RAG para consultar bases de conocimiento de beneficios y políticas. Se integraron citas de fuentes exactas y se evaluó con más de 200 casos de prueba QA para asegurar consistencia y tono consultivo.',
      value: 'Respuestas inmediatas respaldadas por fuentes oficiales, disminución del tiempo de consulta y discurso comercial seguro y estandarizado.',
      facts: ['200+ casos de prueba QA', 'RAG con citas de origen', 'Métricas de consistencia', 'Foco en medios de pago'],
      tags: ['RAG', 'Copilot', 'GenAI', 'Prompt Engineering', 'QA & Validation', 'Gemini'],
      visual: 'knowledge',
    },
    {
      id: 'genai-marketing',
      number: '03',
      short: 'Agente de Piezas & Briefs',
      title: 'Agente de IA para creación de briefs y piezas HTML/Email para Marketing & PMs',
      context: 'Marketing Estratégico & Product Management',
      type: 'Agente Generativo + HTML/CSS Delivery + Variantes',
      status: 'En uso',
      role: 'Diseño de workflows de agentes, prompts y templates responsive',
      thesis: 'El paso de un requerimiento comercial a un brief formal y una pieza funcional suele demorar semanas. Un agente estructurado puede generar el brief y la pieza HTML en paralelo.',
      problem: 'Ciclos lentos de iteración entre las peticiones de los Product Managers y la producción de piezas de campaña (especialmente emails y comunicaciones digitales).',
      build: 'Diseño de un agente inteligente que recibe el pedido comercial (audiencia, propuesta de valor, objetivo), genera un brief estructurado y produce el delivery directo de la pieza en código HTML responsive lista para testear y enviar.',
      value: 'Aceleración drástica de la salida al mercado de campañas, facilitando la alineación inmediata entre Product Managers y equipos de Marketing.',
      facts: ['Brief comercial automático', 'Generación de Email HTML responsive', '3 variantes de tono/copy', 'Delivery inmediato'],
      tags: ['AI Agents', 'HTML/Email Generator', 'Marketing Automation', 'Briefing OS', 'Prompt Engineering'],
      visual: 'content',
    },
    {
      id: 'academic-tracker',
      number: '04',
      short: 'Scrum Master Tracker',
      title: 'Plataforma web de seguimiento para 30+ equipos, notas ponderadas y bitácora',
      context: 'Universidad San Sebastián · Gestión de Proyectos',
      type: 'Aplicación Web + Bitácora + Semáforo de Riesgo',
      status: 'Implementado y en uso',
      role: 'Scrum Master y Desarrollador de la Plataforma',
      thesis: 'Coordinar más de 30 equipos multidisciplinarios exige visibilidad en tiempo real de notas ponderadas, bitácora de reuniones y detección temprana de bloqueos.',
      problem: 'Las evaluaciones, avances y estados de decenas de equipos se dispersaban en planillas desactualizadas, dificultando el seguimiento docente a tiempo.',
      build: 'Desarrollo de una plataforma web centralizada (Vercel, HTML/JS) con módulo de carga de ponderaciones de notas, bitácora de avances por sprint, estado crítico de equipos y tags de seguimiento para facilitar la toma de decisiones basada en desempeño.',
      value: 'Estandarización de criterios de evaluación, orden metodológico ágil y trazabilidad total del progreso de cada equipo.',
      facts: ['30+ equipos coordinados', 'Cálculo de notas ponderadas', 'Bitácora y semáforo de riesgo', 'Trazabilidad de sprints'],
      tags: ['Scrum', 'Vercel', 'JavaScript', 'Gestión Ágil', 'Web App', 'Analytics'],
      visual: 'tracker',
    },
    {
      id: 'crm-lifecycle',
      number: '05',
      short: 'CRM & Lifecycle Visa',
      title: 'Estrategias de ciclo de vida del cliente y seguimiento de iniciativas',
      context: 'Estrategia Regional Visa · Chile y Argentina',
      type: 'Journeys + Dashboards Power BI + Coordinación',
      status: 'Implementación y seguimiento',
      role: 'Consultor de Estrategia, Datos y Articulador de Equipos',
      thesis: 'El cliente no es una masa estática; requiere acciones precisas para su adquisición, activación temprana, uso, recurrencia y reactivación conectadas a analítica.',
      problem: 'Falta de conexión fluida entre las bases generadas por Data Science y la ejecución de campañas comerciales de los Business Analysts y Marketing.',
      build: 'Diseño de customer journeys, segmentaciones accionables y tableros en Power BI para lectura ejecutiva de funnels, monitoreando hitos y detectando oportunidades de optimización y monetización.',
      value: 'Supervisión integral del ciclo de vida del cliente y articulación efectiva de equipos multidisciplinarios en medios de pago.',
      facts: ['Funnel Adquisición a Reactivación', 'Tableros ejecutivos en Power BI', 'Alineación Data Science y Marketing', 'Iniciativas regionales'],
      tags: ['Customer Lifecycle', 'CRM', 'Power BI', 'Marketing Estratégico', 'Medios de Pago'],
      visual: 'control',
    },
  ],
  process: [
    { step: '01', title: 'Diagnosticar el ciclo', desc: 'Evaluar desde la adquisición hasta la retención, entendiendo la rentabilidad y experiencia en cada fase.' },
    { step: '02', title: 'Diseñar la estrategia', desc: 'Definir mecánicas, journeys y segmentaciones viables apoyadas en análisis competitivo.' },
    { step: '03', title: 'Prototipar y probar', desc: 'Validar mediante maquetas o pruebas GenAI antes de un despliegue masivo, minimizando riesgos.' },
    { step: '04', title: 'Monitorear e iterar', desc: 'Crear tableros ejecutivos y medir efectividad y monetización en tiempo real.' },
  ],
  experience: [
    {
      company: 'Artefact Spanish LATAM (ex-Brain Food)',
      role: 'Data Consultant · Strategic Marketing, GenAI & Business Automation',
      period: 'Abr 2026 — Actualidad',
      area: 'Consultoría Estratégica · Visa Regional · Banca',
      description: 'Consultor en iniciativas regionales de Visa para instituciones financieras de Chile y Argentina, actuando como nexo articulador entre estrategia comercial, Data Science, Business Analysts y Marketing.',
      friction: 'Información dispersa en políticas comerciales, desconexión entre modelos predictivos y campañas, y lentitud en la generación de presentaciones directivas.',
      solution: 'Desarrollo de prototipos de copilotos RAG (200+ tests QA), motor de presentaciones ejecutivas HTML->PPTx, diseño de customer journeys (adquisición a reactivación) y tableros Power BI.',
      impact: 'Presentaciones directivas entre Visa y bancos aliados para habilitar nuevos proyectos; transferencia de know-how y adopción institucional de las herramientas y prototipos creados.',
      highlights: [
        'Presentación de propuestas y prototipos en mesas de trabajo conjuntas entre Visa y bancos de la región.',
        'Prototipado de copilotos conversacionales con RAG y validación sistemática con más de 200 casos de prueba.',
        'Diseño y supervisión de customer journeys de medios de pago alineando bases de Data Science con ejecuciones de Marketing.',
        'Creación del motor de presentaciones ejecutivas y automatizaciones con GenAI adoptadas por el equipo.',
      ],
      current: true,
    },
    {
      company: 'Universidad San Sebastián',
      role: 'Scrum Master & Desarrollador Web · Taller de Tecnologías Digitales & Sustentabilidad',
      period: 'Sep 2025 — Jul 2026',
      area: 'Educación Superior · Coordinación Ágil & Fullstack',
      description: 'Lideré la coordinación ágil y seguimiento metodológico de más de 30 equipos multidisciplinarios, desarrollando herramientas ad-hoc para centralizar el control.',
      friction: 'Fragmentación de notas, bitácoras y avances en planillas manuales, dificultando el seguimiento oportuno del rendimiento grupal.',
      solution: 'Diseño y desarrollo de una aplicación web centralizada (Vercel, HTML/JS) para cargar ponderaciones de notas, bitácora de reuniones y semáforos de riesgo por sprint.',
      impact: 'Estandarización de criterios de evaluación, detección temprana de bloqueos en equipos críticos y adopción continua por parte del cuerpo docente.',
      highlights: [
        'Coordinación metodológica de más de 30 equipos simultáneos bajo marco de trabajo Scrum.',
        'Desarrollo de plataforma web de seguimiento con cálculo ponderado de notas y bitácora de reuniones.',
        'Automatización del control de hitos y facilitación de decisiones académicas basadas en métricas de avance.',
      ],
    },
    {
      company: 'Salfa',
      role: 'Analista BI y Gestión Comercial',
      period: 'Dic 2024 — Sep 2025',
      area: 'Automotriz & Maquinaria · Analítica de Negocio',
      description: 'Optimicé la reportería y la gestión comercial mediante diseño de tableros, estructuración de indicadores clave y rediseño de procesos operativos.',
      friction: 'Reportería comercial lenta y fragmentada que demoraba la toma de decisiones operativas en la red comercial.',
      solution: 'Construcción de dashboards en Power BI, automatización en la consolidación de indicadores y reingeniería de flujos de información.',
      impact: 'Reducción drástica en tiempos de generación de informes y mayor visibilidad para la gerencia sobre el cumplimiento de metas comerciales.',
      highlights: [
        'Desarrollo de dashboards ejecutivos en Power BI para monitoreo de ventas y márgenes.',
        'Automatización y estructuración de KPIs comerciales para agilizar la toma de decisiones.',
        'Participación en el rediseño de procesos operativos para reducir cuellos de botella.',
      ],
    },
    {
      company: 'Ludum Bar',
      role: 'Analista de Inteligencia Comercial',
      period: 'Oct 2023 — Feb 2025',
      area: 'Servicios & Gastronomía · Finanzas y Marketing',
      description: 'Analicé la rentabilidad, estructura de pricing y comportamiento de clientes, conectando métricas financieras con la experiencia comercial.',
      friction: 'Desconocimiento del margen real por categoría de producto y falta de análisis en el impacto de promociones.',
      solution: 'Modelación de costos, análisis de elasticidad de precios y seguimiento del patrón de compra y recurrencia de clientes.',
      impact: 'Optimización de la estructura de pricing, maximización de márgenes en productos clave y evaluación precisa de promociones comerciales.',
      highlights: [
        'Modelos de pricing y análisis de rentabilidad por línea de servicio.',
        'Evaluación de efectividad de campañas comerciales basada en datos transaccionales de venta.',
        'Conexión entre indicadores financieros, operaciones y fidelización de clientes.',
      ],
    },
    {
      company: 'GETC Contratista E.I.R.L.',
      role: 'Consultor en Gestión Empresarial',
      period: 'Ene 2023 — Feb 2025',
      area: 'Consultoría de Operaciones & Gestión',
      description: 'Asesoré en modernización administrativa, control de costos operativos y automatización documental para fortalecer la toma de decisiones internas.',
      friction: 'Procesos administrativos descentralizados, control de gastos manual y falta de trazabilidad documental.',
      solution: 'Estructuración de herramientas semiautomatizadas de control presupuestario y digitalización de flujos documentales.',
      impact: 'Mayor disponibilidad y consistencia de información financiera y administrativa para la dirección de la empresa.',
      highlights: [
        'Diseño de herramientas de control presupuestario y seguimiento de costos por proyecto.',
        'Automatización documental para reducir tiempos de procesamiento administrativo.',
        'Modernización de flujos de información para la toma de decisiones gerenciales.',
      ],
    },
  ],
  education: [
    { degree: 'Ingeniería Civil Industrial', institution: 'Universidad San Sebastián', period: '2019 — 2026', note: 'Titulado' },
    { degree: 'Diplomado en Finanzas', institution: 'Universidad San Sebastián', period: '2024 — 2025', note: 'Completado' },
  ],
  capabilities: [
    {
      title: 'Estrategia & Producto',
      description: 'Business Strategy, Product Discovery, Customer Journeys, Benchmarking e Inteligencia Competitiva.',
      evidence: 'Diseño de estrategias regionales de customer lifecycle (adquisición, activación, uso y reactivación) en medios de pago.',
      skills: ['Customer Lifecycle', 'CRM', 'Journeys', 'Product Discovery', 'Competitive Intelligence', 'Stakeholder Management'],
    },
    {
      title: 'IA Aplicada & Automatización',
      description: 'Generative AI, AI Agents, Copilotos RAG, Prompt Engineering, Workflows con LLMs y Automatización de Procesos.',
      evidence: 'Desarrollo de copilotos comerciales auditados con 200+ tests QA y motor de presentaciones HTML->PPTx.',
      skills: ['Generative AI', 'RAG Pipelines', 'AI Prototyping', 'Prompt Engineering', 'AI Agents', 'Automation Workflows'],
    },
    {
      title: 'Data & Analítica de Negocio',
      description: 'Desarrollo de tableros ejecutivos en Power BI, análisis de campañas, funnels transaccionales y segmentación.',
      evidence: 'Monitoreo de métricas comerciales y alineación de bases de Data Science con ejecuciones de Marketing.',
      skills: ['Power BI', 'Funnels de Conversión', 'Segmentación', 'SQL', 'Benchmarks de Industria', 'KPIs Comerciales'],
    },
    {
      title: 'Tecnología & Prototipado Web',
      description: 'Construcción de aplicaciones funcionales, herramientas web de gestión ágil y maquetación responsive.',
      evidence: 'Plataformas desarrolladas en React, HTML/JS, TypeScript y desplegadas en Vercel y Firebase.',
      skills: ['HTML/CSS/JS', 'TypeScript', 'React', 'Tailwind CSS', 'Vercel', 'Firebase/Firestore', 'Google Cloud'],
    },
  ],
  tools: [
    'Google Cloud',
    'Gemini',
    'Claude',
    'GPT-OSS',
    'Google AI Studio',
    'Power BI',
    'Firebase/Firestore',
    'Vercel',
    'TypeScript',
    'React',
    'HTML/CSS/JS',
    'Selenium',
    'BeautifulSoup',
    'Trello',
    'Canva',
  ],
  credentials: [
    {
      title: 'Google Project Management',
      issuer: 'Google',
      date: '2024',
      category: 'Proyectos & Estrategia',
      featured: true,
    },
    {
      title: 'Pensamiento estratégico y mentalidad estratégica',
      issuer: 'Banco Santander',
      date: '2024',
      category: 'Proyectos & Estrategia',
      featured: true,
    },
    {
      title: 'Gestión de Proyectos y Fundamentos Agile',
      issuer: 'Banco Santander',
      date: '2024',
      category: 'Proyectos & Estrategia',
      featured: true,
    },
    {
      title: 'Introducción a la Ciencia de Datos',
      issuer: 'IE University',
      date: '2024',
      category: 'Datos & BI',
      featured: true,
    },
    {
      title: 'Gestión de Proyectos Mineros',
      issuer: 'Certificación Profesional',
      date: '2024',
      category: 'Operaciones & Mejora',
      featured: false,
    },
  ],
};
