export const portfolioData = {
  personalInfo: {
    name: 'Israel Torres',
    fullName: 'Israel Torres López',
    title: 'Ingeniero Civil Industrial · Data Consultant',
    eyebrow: 'Estrategia · Datos · Producto · IA aplicada',
    headline: 'Me cuesta ver algo que puede funcionar mejor y dejarlo igual.',
    description:
      'Soy Israel. Conecto negocio, datos, diseño y tecnología para convertir problemas poco claros en herramientas que alguien realmente pueda usar. No tengo todas las respuestas: pregunto, aprendo rápido, pruebo y vuelvo a mejorar.',
    email: 'itorresl@correo.uss.cl',
    linkedin: 'https://www.linkedin.com/in/israeltorresl',
    github: 'https://github.com/IsraelTorresIndustrial/Israel-Torres-Web',
    location: 'Santiago, Chile',
  },
  heroScenarios: [
    {
      ask: '“Necesitamos una presentación.”',
      question: '¿Y si el proceso pudiera aprender de cada deck?',
      outcome: 'Un motor editable con storyline, layouts, trazabilidad y QA.',
      label: 'Presentaciones → sistema',
    },
    {
      ask: '“La información comercial está dispersa.”',
      question: '¿Qué necesita saber la persona en ese momento?',
      outcome: 'Conocimiento, recomendación y evidencia en una sola experiencia.',
      label: 'Información → decisión',
    },
    {
      ask: '“Son demasiados equipos para seguirlos bien.”',
      question: '¿Cómo vemos quién necesita apoyo antes de que sea tarde?',
      outcome: 'Un tablero que conecta avance, evidencia y próximo paso.',
      label: 'Seguimiento → acompañamiento',
    },
  ],
  metrics: [
    { value: '2', label: 'países', description: 'Iniciativas regionales en Chile y Argentina.' },
    { value: '30+', label: 'equipos', description: 'Coordinación académica multidisciplinaria.' },
    { value: '16', label: 'credenciales', description: 'IA, datos, estrategia, proyectos y mejora.' },
    { value: '5', label: 'sistemas', description: 'Una selección de productos y prototipos propios.' },
  ],
  trustedFor: [
    'Ordenar un problema que llega difuso',
    'Convertir análisis en una historia clara',
    'Prototipar una herramienta para poder discutirla',
    'Subir el estándar visual y funcional de una entrega',
  ],
  principles: [
    {
      number: '01',
      title: 'Empiezo por la persona',
      description: 'Antes de pensar en tecnología, intento entender quién debe usar la solución, qué le cuesta hoy y qué decisión necesita tomar.',
      signal: 'Usuario primero',
    },
    {
      number: '02',
      title: 'Hago visible la idea',
      description: 'Un prototipo permite conversar mejor que diez páginas de supuestos. Construyo para aprender, no para fingir que todo está resuelto.',
      signal: 'Pensar haciendo',
    },
    {
      number: '03',
      title: 'No confundo confianza con evidencia',
      description: 'Me importa que una respuesta pueda explicarse, que lo no evaluado siga siendo no evaluado y que el QA sea honesto.',
      signal: 'Criterio y trazabilidad',
    },
    {
      number: '04',
      title: 'Intento dejar una capacidad',
      description: 'Si una entrega funciona, busco qué parte puede convertirse en método, producto o sistema para no volver a empezar desde cero.',
      signal: 'Más allá del encargo',
    },
  ],
  projects: [
    {
      id: 'commercial-intelligence',
      number: '01',
      short: 'Inteligencia comercial',
      title: 'Un sistema comercial que conversa, compara y recomienda',
      context: 'Producto propio · Banca y medios de pago',
      type: 'RAG + recomendación + experiencia conversacional',
      status: 'MVP funcional y auditado',
      role: 'Concepto, arquitectura de conocimiento, producto, prototipo y QA',
      thesis:
        'Partió como una forma de evitar que un ejecutivo buscara información entre documentos. Terminó conectando conocimiento, conversación consultiva, perfil de cliente, benchmark y recomendación controlada.',
      problem:
        'La información comercial estaba dispersa y una respuesta incorrecta podía ser peor que no responder. Además, ejecutivo y cliente necesitaban experiencias distintas.',
      build:
        'Construí dos interfaces conectadas: un copiloto para el ejecutivo y un asesor para el cliente. El sistema usa 84 fragmentos estructurados, evidencia por niveles, un motor determinístico de recomendación, validadores factuales y estados conversacionales.',
      value:
        'Hace tangible una ruta de producto completa: primero encontrar información, después orientar una conversación y finalmente recomendar con condiciones explícitas y opción de derivación humana.',
      facts: ['84 fragmentos de evidencia', '2 experiencias conectadas', 'Benchmark competitivo', 'Validación factual'],
      tags: ['RAG', 'Product thinking', 'UX conversacional', 'Guardrails', 'Gemini'],
      visual: 'knowledge',
    },
    {
      id: 'presentation-os',
      number: '02',
      short: 'Communication OS',
      title: 'De hacer presentaciones a construir un sistema de comunicación',
      context: 'Executive Communication OS · Producto en evolución',
      type: 'Inteligencia + ejecución + QA visual',
      status: 'Motor local y arquitectura modular',
      role: 'Product owner, arquitectura, dirección visual y ciclo de mejora',
      thesis:
        'El problema no era “hacer un PowerPoint”. Era convertir información de negocio en una historia clara, visual, editable y trazable sin perder criterio en el camino.',
      problem:
        'Análisis, narrativa, diseño y validación suelen mezclarse en un proceso artesanal. Eso dificulta repetir calidad y aprender entre entregas.',
      build:
        'Diseñé un pipeline que separa inteligencia y ejecución: brief, hechos, insights, claims, storyline, especificación, render y QA. Trabaja con 13 familias visuales y conserva editabilidad nativa.',
      value:
        'Transforma una entrega repetitiva en una capacidad reusable que puede producir, revisar y mejorar presentaciones sin esconder las decisiones tomadas.',
      facts: ['13 familias visuales', 'PPTX editable', 'Mapa de fuentes', 'QA de contenido y render'],
      tags: ['Storyline', 'Visual systems', 'python-pptx', 'Multi-agent', 'QA'],
      visual: 'presentation',
    },
    {
      id: 'project-control',
      number: '03',
      short: 'Project Control',
      title: 'Control de iniciativas para coordinar sin reconstruir el estado',
      context: 'Aplicación web · Coordinación de proyectos',
      type: 'Dashboard + Gantt + gestión operativa',
      status: 'Aplicación web con autenticación',
      role: 'Diseño de producto, desarrollo y modelo de seguimiento',
      thesis:
        'Un tablero es útil cuando responde rápido qué avanza, qué está bloqueado y dónde se necesita una decisión; no cuando solo acumula indicadores.',
      problem:
        'Iniciativas, responsables y fechas vivían entre distintas fuentes. El equipo necesitaba una vista ejecutiva y también una forma de editar y gestionar el detalle.',
      build:
        'Desarrollé una aplicación con acceso controlado, dashboard filtrable, métricas, Gantt, listado editable de iniciativas, alertas, responsables y configuración de datos.',
      value:
        'Conecta lectura ejecutiva y operación diaria en una misma superficie, reduciendo la dependencia de consolidaciones manuales.',
      facts: ['Dashboard filtrable', 'Gantt editable', 'Acceso controlado', 'Persistencia en Firebase'],
      tags: ['React', 'Firebase', 'Gantt', 'Project management', 'UX operativa'],
      visual: 'control',
    },
    {
      id: 'genia-content',
      number: '04',
      short: 'GenIA Content',
      title: 'Un flujo creativo que mantiene el brief hasta la entrega',
      context: 'Producto propio · Generación de contenido',
      type: 'Brief + variaciones + imagen + video',
      status: 'Prototipo funcional',
      role: 'Concepto, experiencia, desarrollo e integración con IA',
      thesis:
        'Generar una imagen aislada es fácil. Lo difícil es sostener la intención del brief, comparar alternativas y producir formatos listos para trabajar.',
      problem:
        'La creación con IA se fragmenta cuando concepto, tono, formatos, variaciones y video no comparten un flujo ni una memoria común.',
      build:
        'Diseñé una experiencia paso a paso con brief estructurado, referencias visuales, múltiples variaciones, formatos sociales, generación de imagen y video 1080p, extensiones y exportación agrupada.',
      value:
        'Convierte prompts sueltos en un proceso creativo trazable, comparable y preparado para revisión y entrega.',
      facts: ['7 relaciones de aspecto', 'Imagen y video', 'Variaciones comparables', 'Paquete exportable'],
      tags: ['GenAI', 'Content design', 'Gemini', 'Video', 'Flujos guiados'],
      visual: 'content',
    },
    {
      id: 'scrum-tracker',
      number: '05',
      short: 'Scrum Tracker',
      title: 'Seguimiento que ayuda a acompañar, no solo a controlar',
      context: 'Universidad San Sebastián · Talleres académicos',
      type: 'Equipos + reuniones + evidencia + exportación',
      status: 'Aplicación utilizada en contexto académico',
      role: 'Scrum Master, diseño de proceso y desarrollo de la plataforma',
      thesis:
        'Cuando hay más de 30 equipos, registrar avances no basta. La información debe ayudar a detectar quién necesita apoyo y preparar la próxima conversación.',
      problem:
        'Acuerdos, reuniones, hitos y evidencias estaban distribuidos, limitando la trazabilidad y el acompañamiento oportuno de los proyectos.',
      build:
        'Desarrollé una plataforma con dashboard docente, vista por equipos, modo reunión, historial, configuración, exportación a Excel y permisos diferenciados.',
      value:
        'Centralizó el seguimiento y convirtió datos de avance en una herramienta práctica para acompañar decisiones, reuniones y entregas.',
      facts: ['30+ equipos', 'Modo reunión', 'Roles diferenciados', 'Exportación a Excel'],
      tags: ['Scrum', 'Educación', 'Trazabilidad', 'Firebase', 'Coordinación'],
      visual: 'tracker',
    },
  ],
  process: [
    { step: '01', title: 'Entender', desc: 'Observar el trabajo real, preguntar y encontrar la fricción que vale la pena resolver.' },
    { step: '02', title: 'Ordenar', desc: 'Separar señales, personas, decisiones y restricciones hasta volver claro el desafío.' },
    { step: '03', title: 'Hacer tangible', desc: 'Construir la versión mínima que permita conversar con evidencia y no solo con supuestos.' },
    { step: '04', title: 'Volver a mirar', desc: 'Probar, criticar, corregir y capturar el aprendizaje para que la siguiente versión sea mejor.' },
  ],
  experience: [
    {
      company: 'Artefact Spanish LATAM (ex-Brain Food)',
      role: 'Data Consultant · Strategic Marketing, GenAI & Business Automation',
      period: 'Abr 2026 — Actualidad',
      area: 'Consultoría · Banca y medios de pago',
      description: 'Trabajo en iniciativas regionales para instituciones financieras de Chile y Argentina, conectando estrategia de negocio, CRM, analítica e inteligencia artificial aplicada.',
      highlights: ['Customer lifecycle: adquisición, activación, uso y reactivación', 'Benchmarks de productos, beneficios, campañas y experiencia digital', 'Prototipos y automatizaciones basados en IA', 'Coordinación con Negocio, Marketing, BI y Data Science'],
      current: true,
    },
    {
      company: 'Universidad San Sebastián',
      role: 'Scrum Master · Taller de Tecnologías Digitales',
      period: 'Abr 2026 — Jul 2026',
      area: 'Educación · Tecnología',
      description: 'Coordiné proyectos académicos y desarrollé una aplicación para centralizar avances, reuniones, hitos y entregables.',
      highlights: ['Seguimiento de proyectos', 'Aplicación web de trazabilidad'],
    },
    {
      company: 'Universidad San Sebastián',
      role: 'Scrum Master · Taller de Sustentabilidad',
      period: 'Sep 2025 — Nov 2025',
      area: 'Educación · Coordinación',
      description: 'Lideré el seguimiento de más de 30 equipos multidisciplinarios y diseñé una herramienta semiautomatizada de evaluación y control.',
      highlights: ['30+ equipos', 'Estandarización de criterios'],
    },
    {
      company: 'SALFA',
      role: 'Analista BI y Gestión Comercial',
      period: 'Dic 2024 — Sep 2025',
      area: 'Automotriz · Business Intelligence',
      description: 'Optimicé reportería y procesos comerciales mediante dashboards, automatización y rediseño operativo.',
      highlights: ['Power BI y reportería', 'Reducción de tiempos operativos'],
    },
    {
      company: 'Ludum Bar',
      role: 'Analista de Inteligencia Comercial',
      period: 'Oct 2023 — Feb 2025',
      area: 'Servicios · Analítica comercial',
      description: 'Conecté rentabilidad, pricing y desempeño comercial con decisiones de marketing y experiencia de cliente.',
      highlights: ['Pricing y rentabilidad', 'Marketing y experiencia'],
    },
    {
      company: 'GETC Contratista E.I.R.L.',
      role: 'Consultor en Gestión Empresarial',
      period: 'Ene 2023 — Feb 2025',
      area: 'Gestión · Mejora de procesos',
      description: 'Apoyé la modernización administrativa, el control de costos y la automatización documental de la operación.',
      highlights: ['Control de costos', 'Modernización administrativa'],
    },
  ],
  education: [
    { degree: 'Ingeniería Civil Industrial', institution: 'Universidad San Sebastián', period: '2019 — Ene 2026', note: 'Titulado' },
    { degree: 'Diplomado en Finanzas', institution: 'Universidad San Sebastián', period: '2024 — 2025', note: 'Completado' },
  ],
  capabilities: [
    {
      title: 'Estructurar problemas',
      description: 'Encuentro la pregunta detrás del pedido y traduzco complejidad en una secuencia de decisiones trabajables.',
      evidence: 'Presente en consultoría, coordinación y cada producto que construyo.',
      skills: ['Problem framing', 'Procesos', 'Storyline', 'Project management'],
    },
    {
      title: 'Diseñar contenido que ayuda a decidir',
      description: 'Convierto análisis en narrativas, presentaciones e interfaces donde lo importante se puede ver y entender.',
      evidence: 'Una fortaleza que otros suelen pedirme para mejorar entregables.',
      skills: ['Content design', 'Comunicación ejecutiva', 'UX writing', 'Visualización'],
    },
    {
      title: 'Prototipar productos con IA',
      description: 'Uso código, modelos y automatización para llevar una idea desde el concepto hasta una experiencia que se pueda probar.',
      evidence: 'Copilotos, motores de contenido, sistemas de presentación y herramientas internas.',
      skills: ['React', 'Firebase', 'Gemini', 'RAG', 'Agentes'],
    },
    {
      title: 'Conectar datos, clientes y negocio',
      description: 'Uno contexto comercial, comportamiento, métricas y operación para construir una lectura accionable.',
      evidence: 'Pagos, CRM, customer lifecycle, pricing y Business Intelligence.',
      skills: ['Power BI', 'SQL', 'CRM', 'KPIs', 'Customer lifecycle'],
    },
  ],
  tools: ['Power BI', 'SQL', 'React', 'Firebase', 'Gemini', 'Google Cloud', 'GitHub', 'Python', 'Apps Script', 'AI Studio', 'AJO'],
  credentials: [
    { title: 'Certified Partner Specialist: Gemini Enterprise Agent Development', issuer: 'Google', date: 'Jul 2026', category: 'IA & Cloud', featured: true, validUntil: 'Ene 2027' },
    { title: 'Accelerate Development with Antigravity', issuer: 'Google', date: 'Jul 2026', category: 'IA & Cloud', featured: true },
    { title: 'Google AI', issuer: 'Google', date: 'Jun 2026', category: 'IA & Cloud', featured: true },
    { title: 'Google: Inteligencia Artificial y productividad', issuer: 'Google', date: 'Nov 2024', category: 'IA & Cloud' },
    { title: 'Fundamentos de ChatGPT', issuer: 'Santander Open Academy', date: 'Ene 2025', category: 'IA & Cloud' },
    { title: 'Google Project Management', issuer: 'Google', date: 'May 2025', category: 'Proyectos & Estrategia', featured: true },
    { title: 'Strategic Leadership and Management', issuer: 'University of Illinois Urbana-Champaign', date: 'Jul 2025', category: 'Proyectos & Estrategia', featured: true },
    { title: 'Scrum Foundation Professional Certificate SFPC', issuer: 'CertiProf', date: 'Sep 2025', category: 'Proyectos & Estrategia', validUntil: 'Sep 2026' },
    { title: 'Introduction to Project Management', issuer: 'IBM', date: 'Abr 2025', category: 'Proyectos & Estrategia' },
    { title: 'Gestión de Proyectos y Fundamentos de metodología Agile', issuer: 'Santander Open Academy', date: 'Ene 2025', category: 'Proyectos & Estrategia' },
    { title: 'Pensamiento estratégico y mentalidad estratégica', issuer: 'Santander Open Academy', date: 'Ene 2025', category: 'Proyectos & Estrategia' },
    { title: 'Gestión de proyectos mineros', issuer: 'mine-class.com', date: 'Mar 2026', category: 'Proyectos & Estrategia' },
    { title: 'Power BI', issuer: 'Santander Open Academy', date: 'Dic 2024', category: 'Datos & BI', featured: true },
    { title: 'Introducción a la Ciencia de Datos', issuer: 'IE University', date: 'Nov 2024', category: 'Datos & BI' },
    { title: 'Excel', issuer: 'Santander Open Academy', date: 'Jun 2024', category: 'Datos & BI' },
    { title: 'Lean Management', issuer: 'APRENMIN OTEC', date: 'Mar 2023', category: 'Operaciones & Mejora' },
  ],
};
