export const portfolioData = {
  personalInfo: {
    name: 'Israel Torres',
    fullName: 'Israel Torres',
    title: 'Ingeniero Civil Industrial · Strategy, Product & Applied AI',
    eyebrow: 'CRM, Data, Payments & IA aplicada',
    headline: 'Traduzco problemas de negocio en estrategias, prototipos y soluciones accionables.',
    description: 'Soy Ingeniero Civil Industrial. Mi foco está en articular equipos de Negocio, Marketing, BI y Data Science, y conectar estrategia comercial, analítica e IA para crear herramientas y experiencias que realmente resuelvan problemas. Me gusta tener un tono cercano y humano: no tengo todas las respuestas, pero pregunto, pruebo y construyo para aprender rápido.',
    email: 'itorresl@correo.uss.cl',
    linkedin: 'https://linkedin.com/in/israeltorresl',
    github: 'https://github.com/IsraelTorresIndustrial',
    location: 'Santiago, Chile',
  },
  heroScenarios: [
    {
      ask: '“La información comercial está dispersa y es difícil de encontrar.”',
      question: '¿Qué pasaría si tuviéramos un copiloto que conozca y estructure todo?',
      outcome: 'Un asistente conversacional validado sistemáticamente, que no solo responde sino que apoya decisiones.',
      label: 'De información a decisión (RAG)',
    },
    {
      ask: '“No sabemos en qué etapa del ciclo de vida perdemos al cliente.”',
      question: '¿Y si diseñamos journeys basados en el comportamiento real y datos?',
      outcome: 'Estrategias de adquisición, activación, uso y reactivación conectadas a analítica.',
      label: 'De dudas a ciclos claros (CRM)',
    },
    {
      ask: '“Crear piezas y briefs de marketing toma demasiado tiempo.”',
      question: '¿Podemos usar GenAI para acelerar e iterar consistentemente?',
      outcome: 'Generación y sistematización de comunicaciones y assets en minutos, sin perder calidad.',
      label: 'De cuellos de botella a fluidez (GenAI)',
    },
  ],
  metrics: [
    { value: '2', label: 'países', description: 'Iniciativas regionales de Visa en Chile y Argentina.' },
    { value: '200+', label: 'pruebas', description: 'Casos de prueba para validación de soluciones conversacionales.' },
    { value: '4+', label: 'dominios', description: 'Medios de pago, CRM, inteligencia competitiva y automatización.' },
    { value: '5+', label: 'prototipos', description: 'De flujos conversacionales hasta herramientas de gestión.' },
  ],
  trustedFor: [
    'Articular equipos multidisciplinarios (Negocio, Marketing, BI y Data Science)',
    'Diseñar journeys y estrategias de customer lifecycle',
    'Desarrollar prototipos de IA generativa y herramientas comerciales',
    'Transformar requerimientos difusos en análisis y propuestas accionables',
  ],
  principles: [
    {
      number: '01',
      title: 'Traducción Negocio-Tecnología',
      description: 'Entiendo el idioma de los datos y la tecnología, pero mi foco siempre está en el impacto comercial y la experiencia de quien tomará las decisiones.',
      signal: 'Visión integral',
    },
    {
      number: '02',
      title: 'Pensar haciendo',
      description: 'Creo maquetas funcionales y flujos de product discovery para validar casos de uso antes de escalar a un desarrollo corporativo masivo.',
      signal: 'Prototipado ágil',
    },
    {
      number: '03',
      title: 'Validación sistemática',
      description: 'Un copiloto o asistente solo es útil si genera confianza. Pruebo incansablemente la consistencia de respuestas, fuentes y comportamiento.',
      signal: 'Criterio y QA',
    },
    {
      number: '04',
      title: 'Más allá de la entrega',
      description: 'Si diseño un journey o un brief, busco que se convierta en una capacidad instalada (como un workflow de GenAI) para acelerar la operación diaria.',
      signal: 'Escalabilidad',
    },
  ],
  projects: [
    {
      id: 'copilot-rag',
      number: '01',
      short: 'Copilotos & RAG',
      title: 'Estructurar conocimiento para apoyar decisiones comerciales',
      context: 'Iniciativas Regionales · Medios de Pago',
      type: 'Asistente Digital + RAG + Validación',
      status: 'Prototipos auditados',
      role: 'Product Discovery, Diseño Conversacional y Validación',
      thesis: 'Un ejecutivo necesita confianza en la información. La IA debe estructurar el conocimiento institucional sin inventar respuestas.',
      problem: 'Existía dispersión en las políticas comerciales, dificultando respuestas ágiles a clientes y generando inconsistencias.',
      build: 'Desarrollo de prototipos funcionales de copilotos y experiencias conversacionales. Se integró RAG y se evaluó con más de 200 casos de prueba para afinar fuentes y comportamiento.',
      value: 'Redujo el tiempo de búsqueda de información y brindó seguridad en el discurso comercial gracias a un QA profundo.',
      facts: ['200+ casos de prueba', 'RAG y GenAI', 'Benchmark ejecutivo', 'Foco en consistencia'],
      tags: ['Copilot', 'RAG', 'Prompt Engineering', 'Product Prototyping', 'Gemini'],
      visual: 'knowledge',
    },
    {
      id: 'crm-lifecycle',
      number: '02',
      short: 'CRM & Lifecycle',
      title: 'Estrategias de ciclo de vida para instituciones financieras',
      context: 'Estrategia Regional Visa · Chile y Argentina',
      type: 'Journeys + Segmentación + Analítica',
      status: 'Implementación y seguimiento',
      role: 'Consultor de Estrategia y Datos',
      thesis: 'El cliente no es una masa estática; requiere acciones precisas para su adquisición, activación, uso y reactivación.',
      problem: 'Falta de conexión entre el comportamiento del usuario y las campañas comerciales.',
      build: 'Diseño de journeys, segmentaciones y mecánicas de campaña para diferentes etapas del funnel, apoyado por dashboards en Power BI para una lectura ejecutiva.',
      value: 'Identificación de oportunidades de monetización, optimización de campañas y mayor recurrencia de los usuarios.',
      facts: ['Adquisición y activación', 'Uso y recurrencia', 'Funnels en Power BI', 'Visión 360 del ciclo'],
      tags: ['CRM', 'Customer Lifecycle', 'Power BI', 'Marketing Estratégico', 'Medios de Pago'],
      visual: 'presentation',
    },
    {
      id: 'genai-marketing',
      number: '03',
      short: 'GenAI para Marketing',
      title: 'Sistematizar creación de briefs y comunicaciones comerciales',
      context: 'Marketing Estratégico · Automatización',
      type: 'Generación + Iteración + HTML',
      status: 'En uso',
      role: 'Diseño de workflows e implementación',
      thesis: 'La creación repetitiva de briefs y piezas visuales desgasta a los equipos creativos y demora la salida al mercado.',
      problem: 'Tiempos de iteración altos y falta de consistencia en requerimientos comerciales cruzados.',
      build: 'Aplicación de GenAI para acelerar iteraciones visuales, sistematizar briefs y generar código HTML/comunicaciones estructuradas desde cero.',
      value: 'Velocidad y consistencia en campañas, permitiendo a los equipos enfocarse en la estrategia y no solo en la ejecución.',
      facts: ['Sistematización de briefs', 'Generación de HTML/CSS', 'Iteración visual', 'Mayor velocidad'],
      tags: ['GenAI', 'Marketing Automations', 'Workflows', 'Claude', 'GPT'],
      visual: 'content',
    },
    {
      id: 'academic-tracker',
      number: '04',
      short: 'Scrum Tracker',
      title: 'Plataforma web para coordinar sin perder la pista',
      context: 'Universidad San Sebastián · Gestión Académica',
      type: 'Desarrollo web + Gestión de hitos',
      status: 'En uso',
      role: 'Scrum Master y Desarrollador',
      thesis: 'Administrar más de 30 equipos exige herramientas que automaticen el seguimiento y destaquen quién requiere atención.',
      problem: 'La información y evaluaciones de decenas de equipos se dispersaban, limitando el apoyo a tiempo.',
      build: 'Desarrollo de una aplicación web centralizada (Vercel, HTML/JS) y herramientas semiautomatizadas para evaluar desempeño y controlar hitos.',
      value: 'Estandarizó criterios, ordenó metodológicamente a los equipos y brindó trazabilidad total del progreso.',
      facts: ['30+ equipos coordinados', 'Herramienta web', 'Evaluación automatizada', 'Gestión ágil'],
      tags: ['Scrum', 'Vercel', 'JavaScript', 'Gestión de Proyectos'],
      visual: 'tracker',
    },
  ],
  process: [
    { step: '01', title: 'Diagnosticar el ciclo', desc: 'Evaluar desde la adquisición hasta la retención, entendiendo la rentabilidad y experiencia en cada fase.' },
    { step: '02', title: 'Diseñar la estrategia', desc: 'Definir mecánicas, journeys y segmentaciones viables apoyadas en análisis competitivo.' },
    { step: '03', title: 'Prototipar y probar', desc: 'Validar mediante maquetas o pruebas GenAI antes de un despliegue masivo, minimizando riesgos.' },
    { step: '04', title: 'Monitorear e iterar', desc: 'Crear tableros ejecutivos y medir efectividad y monetización en tiempo real.' },
  ],
  experience: [
    {
      company: 'Artefact Spanish LATAM (ex-Brain Food)',
      role: 'Data Consultant · Strategic Marketing, GenAI & Business Automation',
      period: 'Abr 2026 — Actualidad',
      area: 'Consultoría · Visa · Instituciones Financieras',
      description: 'Consultor en iniciativas regionales de Visa para Chile y Argentina, uniendo estrategia comercial, CRM, analítica e IA aplicada en medios de pago.',
      highlights: ['Diseño de estrategias de customer lifecycle (adquisición a reactivación) y diseño de journeys.', 'Prototipado de copilotos comerciales con GenAI y RAG, con más de 200 casos de validación.', 'Aplicación de GenAI en Marketing para sistematizar briefs e iterar piezas rápidamente.', 'Diseño de dashboards en Power BI, benchmarks de mercado y análisis competitivo.'],
      current: true,
    },
    {
      company: 'Universidad San Sebastián',
      role: 'Scrum Master · Taller de Tecnologías Digitales',
      period: 'Abr 2026 — Jul 2026',
      area: 'Educación · Coordinación Ágil',
      description: 'Coordiné el seguimiento de proyectos académicos, hitos y entregables de equipos multidisciplinarios.',
      highlights: ['Desarrollo de aplicación web de seguimiento para centralizar avances y mejorar la trazabilidad.'],
    },
    {
      company: 'Universidad San Sebastián',
      role: 'Scrum Master · Taller de Sustentabilidad',
      period: 'Sep 2025 — Nov 2025',
      area: 'Educación · Gestión de Equipos',
      description: 'Lideré la coordinación de más de 30 equipos multidisciplinarios.',
      highlights: ['Aseguramiento del orden metodológico y diseño de una herramienta semiautomatizada de evaluación y control.'],
    },
    {
      company: 'Salfa',
      role: 'Analista BI y Gestión Comercial',
      period: 'Dic 2024 — Sep 2025',
      area: 'Automotriz · Analítica',
      description: 'Optimicé la reportería y gestión comercial para apoyar decisiones operativas.',
      highlights: ['Dashboards, automatización de indicadores y rediseño de procesos para reducir tiempos de ejecución.'],
    },
    {
      company: 'Ludum Bar',
      role: 'Analista de Inteligencia Comercial',
      period: 'Oct 2023 — Feb 2025',
      area: 'Servicios · Finanzas y Marketing',
      description: 'Analicé rentabilidad y desempeño comercial, conectando métricas financieras con operaciones y experiencia.',
      highlights: ['Evaluación de iniciativas, análisis de pricing y comportamiento de clientes.'],
    },
    {
      company: 'GETC Contratista E.I.R.L.',
      role: 'Consultor en Gestión Empresarial',
      period: 'Ene 2023 — Feb 2025',
      area: 'Consultoría · Operaciones',
      description: 'Apoyé la modernización administrativa, control de costos y automatización documental.',
      highlights: ['Estructuración de herramientas de control para mejorar la toma de decisiones internas.'],
    },
  ],
  education: [
    { degree: 'Ingeniería Civil Industrial', institution: 'Universidad San Sebastián', period: '2019 — 2026', note: 'Titulado' },
    { degree: 'Diplomado en Finanzas', institution: 'Universidad San Sebastián', period: '2024 — 2025', note: 'Completado' },
  ],
  capabilities: [
    {
      title: 'Estrategia & Producto',
      description: 'Business Strategy, Product Discovery, Customer Journeys e Inteligencia Competitiva.',
      evidence: 'Desarrollo de estrategias regionales de ciclo de vida (adquisición, uso y reactivación).',
      skills: ['Customer Lifecycle', 'CRM', 'Journeys', 'Product Discovery', 'Strategy'],
    },
    {
      title: 'IA & Automatización',
      description: 'Generative AI, AI Agents, Copilotos, RAG, Prompt Engineering y Automatización de flujos.',
      evidence: 'Prototipos de asistentes comerciales auditados con más de 200 casos de prueba.',
      skills: ['Generative AI', 'RAG', 'AI Prototyping', 'Prompt Engineering', 'Workflows'],
    },
    {
      title: 'Data & Analítica',
      description: 'Desarrollo de tableros ejecutivos, análisis de campañas, funnels y segmentación.',
      evidence: 'Diseño de dashboards en Power BI para lectura ejecutiva de efectividad comercial.',
      skills: ['Power BI', 'Funnels', 'Segmentación', 'SQL', 'Benchmarks'],
    },
    {
      title: 'Tecnología & Frontend',
      description: 'Construcción de interfaces funcionales, herramientas de seguimiento web y maquetación comercial.',
      evidence: 'Herramientas creadas en React, HTML/JS y alojadas en Vercel/Firebase.',
      skills: ['HTML/CSS/JS', 'Vercel', 'Firebase', 'React', 'Google Cloud'],
    },
  ],
  tools: ['Power BI', 'Google Cloud', 'Gemini', 'Claude', 'GPT-OSS', 'AI Studio', 'Firebase/Firestore', 'Vercel', 'HTML/CSS/JS', 'Selenium', 'BeautifulSoup', 'Trello', 'Canva'],
  credentials: [
    { title: 'Google Project Management', issuer: 'Google', date: '2024', category: 'Proyectos & Estrategia', featured: true },
    { title: 'Pensamiento estratégico y mentalidad estratégica', issuer: 'Santander', date: '2024', category: 'Proyectos & Estrategia', featured: true },
    { title: 'Gestión de Proyectos y Fundamentos Agile', issuer: 'Santander', date: '2024', category: 'Proyectos & Estrategia' },
    { title: 'Introducción a la Ciencia de Datos', issuer: 'IE University', date: '2024', category: 'Datos & BI', featured: true },
  ],
};
